# -*- coding: utf-8 -*-
"""Phantompressure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNYEdEXEGs9xOpvHnUb8bHOls2aNy9CQ
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
from IPython.display import HTML

# =============================================================================
# 1. FLUX RECONSTRUCTION SETUP UTILITIES
# =============================================================================

def legendre_poly_and_deriv(n, x):
    """
    Evaluates the Legendre polynomial P_n(x) and its derivative P'_n(x)
    using stable recurrence relations.
    """
    if n == 0:
        return 1.0, 0.0
    elif n == 1:
        return x, 1.0
    p0, dp0 = 1.0, 0.0
    p1, dp1 = x, 1.0
    for k in range(2, n + 1):
        pk = ((2*k - 1)*x*p1 - (k - 1)*p0) / k
        dpk = dp0 + (2*k - 1)*p1
        p0, p1 = p1, pk
        dp0, dp1 = dp1, dpk
    return p1, dp1

def setup_fr(N):
    """
    Sets up Flux Reconstruction matrices and vectors for polynomial degree N.
    Uses Gauss-Legendre points as solution points.
    """
    r, w = np.polynomial.legendre.leggauss(N + 1)
    w = w / 2.0  # Normalize weights to sum to 1.0 (on domain length of 2)
    Np = N + 1

    # Precompute derivative matrix D (D_ij = l_j'(r_i)) & boundary extrapolators
    D = np.zeros((Np, Np))
    V_L = np.zeros(Np)
    V_R = np.zeros(Np)

    for j in range(Np):
        # Evaluate Lagrange basis at borders r = -1 and r = 1
        num_L, den = 1.0, 1.0
        num_R = 1.0
        for k in range(Np):
            if k != j:
                num_L *= (-1.0 - r[k])
                num_R *= (1.0 - r[k])
                den *= (r[j] - r[k])
        V_L[j] = num_L / den
        V_R[j] = num_R / den

        # Calculate derivatives
        for i in range(Np):
            if i != j:
                prod = 1.0
                for k in range(Np):
                    if k != j and k != i:
                        prod *= (r[i] - r[k])
                D[i, j] = prod / den
            else:
                s = sum(1.0 / (r[j] - r[k]) for k in range(Np) if k != j)
                D[i, j] = s

    # Radau correction function derivatives for DG equivalence
    g_L_prime = np.zeros(Np)
    g_R_prime = np.zeros(Np)
    for i in range(Np):
        _, dP_N = legendre_poly_and_deriv(N, r[i])
        _, dP_Np1 = legendre_poly_and_deriv(N + 1, r[i])
        g_L_prime[i] = ((-1.0)**N / 2.0) * (dP_N - dP_Np1)
        g_R_prime[i] = (0.5) * (dP_N + dP_Np1)

    return r, w, D, V_L, V_R, g_L_prime, g_R_prime

# =============================================================================
# 2. PHYSICS & THERMODYNAMICS HELPERS
# =============================================================================

def get_pressure(U, gamma=1.4):
    """Computes physical thermodynamic pressure."""
    rho = U[0]
    rhou = U[1]
    E = U[2]
    return (gamma - 1.0) * (E - 0.5 * rhou**2 / rho)

def get_entropy(U, gamma=1.4):
    """Computes physical entropy s = ln(P/rho^gamma)."""
    rho = U[0]
    P = get_pressure(U, gamma)
    # Clip for safety before log
    return np.log(np.maximum(P, 1e-14) / np.maximum(rho, 1e-14)**gamma)

def get_flux(U, theta, gamma=1.4):
    """
    Computes the 1D physical flux vector incorporating regularized pressure
    for the momentum and energy equations.
    """
    rho = U[0]
    rhou = U[1]
    E = U[2]
    S = U[3] # S = rho * P_phan

    P_phys = (gamma - 1.0) * (E - 0.5 * rhou**2 / rho)
    P_reg = P_phys + theta * (P_phys - S / rho)

    F = np.zeros_like(U)
    F[0] = rhou
    F[1] = rhou**2 / rho + P_reg
    F[2] = (E + P_reg) * (rhou / rho)
    F[3] = rhou * (S / rho)
    return F, P_reg, P_phys

# =============================================================================
# 3. ZHANG-SHU POSITIVITY LIMITERS
# =============================================================================

def apply_zhang_shu_limiter(U, w, V_L, V_R, N_cells, Np, gamma=1.4):
    """
    UPDATED: Vectorized Zhang-Shu limiter that checks both internal solution
    points AND extrapolated interface points to prevent Riemann solver crashes.
    Features a numerically stable quadratic root finder.
    """
    eps = 1e-12
    U_avg = np.sum(U * w[None, None, :], axis=2)

    # Helper to get all points (internal + boundaries) to check for positivity
    def get_all_points(U_curr):
        U_L = np.einsum('j,cij->ci', V_L, U_curr)
        U_R = np.einsum('j,cij->ci', V_R, U_curr)
        return np.concatenate([U_curr, U_L[:, :, None], U_R[:, :, None]], axis=2)

    U_check = get_all_points(U)

    # ---- DENSITY LIMITING ----
    rho_min = np.min(U_check[0, :, :], axis=1)
    theta_rho = np.ones(N_cells)
    idx = rho_min < eps

    if np.any(idx):
        denom = U_avg[0, idx] - rho_min[idx]
        denom = np.where(denom < 1e-14, 1.0, denom)
        theta_rho[idx] = (U_avg[0, idx] - eps) / denom
        theta_rho = np.clip(theta_rho, 0.0, 1.0)

        for c in range(4):
            U[c, :, :] = U_avg[c, :, None] + theta_rho[:, None] * (U[c, :, :] - U_avg[c, :, None])

    # Recompute averages and boundaries after density limiting
    U_avg = np.sum(U * w[None, None, :], axis=2)
    U_check = get_all_points(U)

    # ---- PRESSURE LIMITING ----
    theta_P = np.ones(N_cells)
    # Loop over internal points (Np) AND the 2 boundary points
    for j in range(Np + 2):
        U_j = U_check[:, :, j]
        P_j = get_pressure(U_j, gamma)
        idx = P_j < eps

        if np.any(idx):
            rho_avg = U_avg[0, idx]
            rhou_avg = U_avg[1, idx]
            E_avg = U_avg[2, idx]
            E_eps_avg = E_avg - eps / (gamma - 1.0)

            d_rho = U_j[0, idx] - rho_avg
            d_rhou = U_j[1, idx] - rhou_avg
            d_E = U_j[2, idx] - E_avg

            a_q = d_rho * d_E - 0.5 * d_rhou**2
            b_q = rho_avg * d_E + E_eps_avg * d_rho - rhou_avg * d_rhou
            c_q = rho_avg * E_eps_avg - 0.5 * rhou_avg**2

            # Stable quadratic root finding
            disc = np.maximum(b_q**2 - 4.0 * a_q * c_q, 0.0)
            sign_b = np.where(b_q >= 0, 1.0, -1.0)
            q = -0.5 * (b_q + sign_b * np.sqrt(disc))

            is_linear = np.abs(a_q) < 1e-14
            t1 = np.zeros_like(a_q)
            t2 = np.zeros_like(a_q)

            q_safe = np.where(np.abs(q) < 1e-14, 1e-14, q)
            t1[~is_linear] = q[~is_linear] / a_q[~is_linear]
            t2[~is_linear] = c_q[~is_linear] / q_safe[~is_linear]

            t_linear = np.zeros_like(a_q)
            b_safe = np.where(np.abs(b_q) < 1e-14, 1.0, b_q)
            t_linear[is_linear] = -c_q[is_linear] / b_safe[is_linear]

            def get_valid_root(r1, r2):
                v1 = np.where((r1 >= -1e-8) & (r1 <= 1.0 + 1e-8), r1, 10.0)
                v2 = np.where((r2 >= -1e-8) & (r2 <= 1.0 + 1e-8), r2, 10.0)
                return np.minimum(v1, v2)

            t_sel = np.where(is_linear, t_linear, get_valid_root(t1, t2))
            t_sel = np.clip(t_sel, 0.0, 1.0)

            theta_P[idx] = np.minimum(theta_P[idx], t_sel)

    for c in range(4):
        U[c, :, :] = U_avg[c, :, None] + theta_P[:, None] * (U[c, :, :] - U_avg[c, :, None])

    return U

def apply_entropy_limiter(U, w, N_cells, gamma=1.4):
    """
    Local Minimum Entropy Limiter based on bisection search.
    Ensures cell entropy >= min(entropy of cell and its neighbors).
    """
    U_avg = np.sum(U * w[None, None, :], axis=2)
    s_avg_all = get_entropy(U_avg, gamma)

    # Define local minimum entropy targets (3-cell stencil)
    s_min_target = np.zeros(N_cells)
    for i in range(N_cells):
        im1 = max(0, i-1)
        ip1 = min(N_cells-1, i+1)
        s_min_target[i] = min(s_avg_all[im1], s_avg_all[i], s_avg_all[ip1])

    tol = 1e6    # ATTENTION: This tolerance is set to disable the entropy limiter entirely
    max_iter = 8

    # Check which cells violate the local minimum entropy
    s_points = get_entropy(U, gamma)
    s_min_points = np.min(s_points, axis=1)
    violating_cells = s_min_points < (s_min_target - tol)

    if not np.any(violating_cells):
        return U

    # Bisection search to find theta for U_limited = U_avg + theta * (U - U_avg)
    theta_L = np.zeros(N_cells)
    theta_R = np.ones(N_cells)
    theta = np.ones(N_cells)

    for _ in range(max_iter):
        theta = 0.5 * (theta_L + theta_R)
        # Test conservative state
        U_test = U_avg[:, :, None] + theta[None, :, None] * (U - U_avg[:, :, None])
        s_test = get_entropy(U_test, gamma)
        s_min_test = np.min(s_test, axis=1)

        success = s_min_test >= (s_min_target - tol)
        theta_L = np.where(success, theta, theta_L)
        theta_R = np.where(~success, theta, theta_R)

    # Final update for all violating cells
    theta_final = theta_L
    for c in range(4):
        U[c, violating_cells, :] = U_avg[c, violating_cells, None] + theta_final[violating_cells, None] * (U[c, violating_cells, :] - U_avg[c, violating_cells, None])

    return U

# =============================================================================
# 4. SOLVER RUN KERNEL WITH OPERATOR SPLITTING
# =============================================================================

def compute_rhs(U, dx, N_cells, Np, r, w, D, V_L, V_R, g_L_prime, g_R_prime, theta, gamma, U_fixed_L=None, U_fixed_R=None):
    """
    Computes the spatial Flux Reconstruction derivative operator dF/dx.
    Updated to handle fixed constant boundary condition on both sides.
    """
    # Extrapolate internal states to boundaries (Interfaces 0 and N_cells)
    U_L = np.einsum('j,cij->ci', V_L, U)
    U_R = np.einsum('j,cij->ci', V_R, U)

    # Establish interface states
    U_int_L = np.zeros((4, N_cells + 1))
    U_int_R = np.zeros((4, N_cells + 1))
    U_int_L[:, 1:-1] = U_R[:, :-1]
    U_int_R[:, 1:-1] = U_L[:, 1:]

    # ----------------- LEFT BOUNDARY (Interface 0) -----------------
    # Interior state is on the Right of Interface 0
    U_int_R[:, 0] = U_L[:, 0]

    if U_fixed_L is not None:
        # Weak Dirichlet / Inflow Boundary
        U_int_L[:, 0] = U_fixed_L
    else:
        # Supersonic/Extrapolated Inflow
        U_int_L[:, 0] = U_L[:, 0]


    # ----------------- RIGHT BOUNDARY (Interface -1) -----------------
    # Interior state is on the Left of Interface N_cells (index -1)
    U_int_L[:, -1] = U_R[:, -1]

    if U_fixed_R is not None:
        # WEAK SUBSONIC OUTFLOW: Extrapolate rho and momentum, impose pressure
        rho_int = U_R[0, -1]
        rhou_int = U_R[1, -1]

        # Target physical pressure from your fixed state
        P_out = (gamma - 1.0) * (U_fixed_R[2] - 0.5 * U_fixed_R[1]**2 / U_fixed_R[0])

        # Construct the Ghost State (U_int_R)
        U_ghost = np.zeros(4)
        U_ghost[0] = rho_int  # Extrapolate density
        U_ghost[1] = rhou_int # Extrapolate momentum
        U_ghost[2] = P_out / (gamma - 1.0) + 0.5 * rhou_int**2 / rho_int # Impose pressure
        U_ghost[3] = rho_int * P_out # Sync the phantom pressure to avoid artificial regularized jumps

        U_int_R[:, -1] = U_ghost
    else:
        # WEAK SUPERSONIC OUTFLOW: Simple extrapolation
        # Set ghost state slightly offset or matching to allow the Riemann solver to stay active
        U_int_R[:, -1] = U_R[:, -1]

    # Interface flux calculations
    F_int_L, Preg_int_L, P_int_L = get_flux(U_int_L, theta, gamma)
    F_int_R, Preg_int_R, P_int_R = get_flux(U_int_R, theta, gamma)

    u_int_L = U_int_L[1] / U_int_L[0]
    u_int_R = U_int_R[1] / U_int_R[0]
    a_int_L = np.sqrt(gamma * np.maximum(Preg_int_L, P_int_L) / U_int_L[0])
    a_int_R = np.sqrt(gamma * np.maximum(Preg_int_R, P_int_R) / U_int_R[0])

    C_max = np.maximum(np.abs(u_int_L) + a_int_L, np.abs(u_int_R) + a_int_R)
    F_com = 0.5 * (F_int_L + F_int_R) - 0.5 * C_max[None, :] * (U_int_R - U_int_L)

    # Compute fluxes inside elements
    F_sol, _, _ = get_flux(U, theta, gamma)
    F_L = np.einsum('j,cij->ci', V_L, F_sol)
    F_R = np.einsum('j,cij->ci', V_R, F_sol)

    # Reconstruct spatial derivative
    RHS = np.einsum('jk,cik->cij', D, F_sol)
    RHS += np.einsum('ci,j->cij', F_com[:, :-1] - F_L, g_L_prime)
    RHS += np.einsum('ci,j->cij', F_com[:, 1:] - F_R, g_R_prime)
    RHS *= (2.0 / dx)

    return RHS

def compute_tau(U, dx, C_tau, w, gamma=1.4):
    """Computes the local non-equilibrium relaxation time scale tau per cell."""
    U_avg = np.sum(U * w[None, None, :], axis=2)
    rho_avg = U_avg[0]
    u_avg = U_avg[1] / rho_avg
    P_avg = np.maximum(get_pressure(U_avg, gamma), 1e-12)
    a_avg = np.sqrt(gamma * P_avg / rho_avg)
    return C_tau * dx / (a_avg + np.abs(u_avg) + 1e-12)

def relax_step(U, dt, tau_cell, gamma=1.4):
    """Applies the analytical operator splitting solution to update phantom pressure."""
    rho = U[0]
    rhou = U[1]
    E = U[2]
    S = U[3]

    P_phys = (gamma - 1.0) * (E - 0.5 * rhou**2 / rho)
    exp_factor = np.exp(-dt / tau_cell)[:, None]

    U[3] = rho * P_phys + (S - rho * P_phys) * exp_factor
    return U

# =============================================================================
# 5. CORE SOLVER WRAPPER
# =============================================================================

def run_solver(case_name="sod", N_cells=150, N=2, C_tau=0.2, theta=1.0, cfl=0.15):
    """
    Executes the Euler solver with SSPRK3 time integration and Operator Splitting
    for the non-equilibrium phantom pressure.
    """
    gamma = 1.4
    r, w, D, V_L, V_R, g_L_prime, g_R_prime = setup_fr(N)
    Np = N + 1

    # Spatial domain setup
    if case_name == "sod":
        x_min, x_max = 0.0, 1.0
        t_end = 0.20
    elif case_name == "shu_osher":
        x_min, x_max = -5.0, 5.0
        t_end = 1.80
    else:
        raise ValueError("Unknown test case.")

    dx = (x_max - x_min) / N_cells
    x_faces = np.linspace(x_min, x_max, N_cells + 1)
    x_sol = np.zeros((N_cells, Np))
    for i in range(N_cells):
        x_sol[i, :] = x_faces[i] + 0.5 * (1.0 + r) * dx

    # Initial Conditions
    rho_init = np.zeros_like(x_sol)
    u_init = np.zeros_like(x_sol)
    P_init = np.zeros_like(x_sol)

    # Smoothing factor
    delta = dx * 0.1

    if case_name == "sod":
        x0 = 0.5
        S = 1.0 / (1.0 + np.exp((x_sol - x0) / (delta / 5.0)))
        rho_init = 0.125 + (1.0 - 0.125) * S
        P_init = 0.1 + (1.0 - 0.1) * S
        u_init[:] = 0.0
    elif case_name == "shu_osher":
        x0 = -4.0
        S = 1.0 / (1.0 + np.exp((x_sol - x0) / (delta / 5.0)))
        rho_jump = 3.857143
        u_jump = 2.629369
        P_jump = 10.33333

        rho_init = (1.0 + 0.2 * np.sin(5.0 * x_sol)) * (1.0 - S) + rho_jump * S
        u_init = 0.0 * (1.0 - S) + u_jump * S
        P_init = 1.0 * (1.0 - S) + P_jump * S

    # Set conserved variables: [rho, rho*u, E, rho*P_phan]
    U = np.zeros((4, N_cells, Np))
    U[0] = rho_init
    U[1] = rho_init * u_init
    U[2] = P_init / (gamma - 1.0) + 0.5 * rho_init * u_init**2
    U[3] = rho_init * P_init

    U = apply_zhang_shu_limiter(U, w, V_L, V_R, N_cells, Np, gamma)
    U = apply_entropy_limiter(U, w, N_cells, gamma)

    # Store fixed boundary values from initial state
    U_fixed_L = np.einsum('j,cj->c', V_L, U[:, 0, :])
    U_fixed_R = np.einsum('j,cj->c', V_R, U[:, -1, :])

    t = 0.0
    step = 0
    u_save = [U.copy()]
    t_save = [t]

    print(f"\n--- Initiating Run: {case_name.upper()} (Cells={N_cells}, Degree={N}) ---")

    while t < t_end:
        # Time-step calculation
        u = U[1] / U[0]
        P_phys = get_pressure(U, gamma)
        a = np.sqrt(gamma * np.maximum(P_phys, 1e-12) / U[0])
        lambda_max = np.max(np.abs(u) + a)

        dt = cfl * dx / ((2 * N + 1) * lambda_max)
        if t + dt > t_end:
            dt = t_end - t

        # 1. Compute non-equilibrium relaxation scale tau
        tau_cell = compute_tau(U, dx, C_tau, w, gamma)

        # 2. Time step: Pure Advection (SSPRK3)
        # Stage 1
        RHS1 = compute_rhs(U, dx, N_cells, Np, r, w, D, V_L, V_R, g_L_prime, g_R_prime, theta, gamma, U_fixed_L, U_fixed_R)
        U1 = U - dt * RHS1
        U1 = apply_zhang_shu_limiter(U1, w, V_L, V_R, N_cells, Np, gamma)
        U1 = apply_entropy_limiter(U1, w, N_cells, gamma)

        # Intermediate Relaxation for Stage 1
        tau_cell1 = compute_tau(U1, dx, C_tau, w, gamma)
        U1 = relax_step(U1, dt, tau_cell1, gamma)  # <-- Relax here!

        # Stage 2
        RHS2 = compute_rhs(U1, dx, N_cells, Np, r, w, D, V_L, V_R, g_L_prime, g_R_prime, theta, gamma, U_fixed_L, U_fixed_R)
        U2 = 0.75 * U + 0.25 * (U1 - dt * RHS2)
        U2 = apply_zhang_shu_limiter(U2, w, V_L, V_R, N_cells, Np, gamma)
        U2 = apply_entropy_limiter(U2, w, N_cells, gamma)

        # Intermediate Relaxation for Stage 2
        tau_cell2 = compute_tau(U2, dx, C_tau, w, gamma)
        U2 = relax_step(U2, 0.25 * dt, tau_cell2, gamma)

        # Stage 3
        RHS3 = compute_rhs(U2, dx, N_cells, Np, r, w, D, V_L, V_R, g_L_prime, g_R_prime, theta, gamma, U_fixed_L, U_fixed_R)
        U_new = (1.0/3.0) * U + (2.0/3.0) * (U2 - dt * RHS3)
        U_new = apply_zhang_shu_limiter(U_new, w, V_L, V_R, N_cells, Np, gamma)
        U_new = apply_entropy_limiter(U_new, w, N_cells, gamma)

        # Intermediate Relaxation for Stage 3
        tau_cell3 = compute_tau(U_new, dx, C_tau, w, gamma)
        U_new = relax_step(U_new, (2.0/3.0) * dt, tau_cell3, gamma)

        #    # 3. Time step: Local Analytical Relaxation Step
        #    U_new = relax_step(U_new, dt, tau_cell, gamma)

        U = U_new.copy()
        t += dt
        step += 1

        if step % 100 == 0 or t >= t_end:
            u_save.append(U.copy())
            t_save.append(t)

        if step % 500 == 0 or t >= t_end:
            print(f"Iteration: {step:4d} | Simulated Time: {t:6.4f}s | Step Size dt: {dt:6.4e}s")

    return x_sol.flatten(), u_save, t_save, gamma, theta

# =============================================================================
# 6. HTML5 ANIMATION ENGINE
# =============================================================================

def generate_animation_html(x, u_history, t_history, gamma, theta, case_title):
    fig, axes = plt.subplots(2, 2, figsize=(11, 7))
    fig.suptitle(f"1D High-Order Flux Reconstruction ({case_title.upper()}) with Phantom Pressure", fontsize=14, fontweight='bold')

    ax_rho, ax_vel = axes[0, 0], axes[0, 1]
    ax_pres, ax_noneq = axes[1, 0], axes[1, 1]

    rho_max = np.max([np.max(u[0]) for u in u_history]) * 1.1
    vel_max = np.max([np.max(u[1]/u[0]) for u in u_history]) * 1.1
    vel_min = np.min([np.min(u[1]/u[0]) for u in u_history]) - 0.2
    pres_max = np.max([np.max(get_pressure(u, gamma)) for u in u_history]) * 1.1

    # Precompute non-equilibrium bounds for plot scaling
    all_noneq = [ (get_pressure(u, gamma) - (u[3]/u[0])).flatten() for u in u_history ]
    noneq_min = np.min(all_noneq)
    noneq_max = np.max(all_noneq)
    noneq_range = max(abs(noneq_min), abs(noneq_max)) * 1.1

    line_rho, = ax_rho.plot([], [], 'b-', lw=2, label=r'$\rho$ (Density)')
    line_vel, = ax_vel.plot([], [], 'r-', lw=2, label=r'$u$ (Velocity)')
    line_pres, = ax_pres.plot([], [], 'g-', lw=2, label=r'$P_{phys}$ (Pressure)')
    line_noneq, = ax_noneq.plot([], [], 'k-', lw=1.5, label=r'$P_{phys} - P_{phan}$')

    for ax in [ax_rho, ax_vel, ax_pres, ax_noneq]:
        ax.set_xlim(x.min(), x.max())
        ax.grid(True, linestyle=':', alpha=0.6)
        ax.legend(loc='upper right')

    ax_rho.set_ylim(-0.1, rho_max)
    ax_vel.set_ylim(vel_min, vel_max)
    ax_pres.set_ylim(-0.1, pres_max)
    ax_noneq.set_ylim(-noneq_range, noneq_range)
    ax_noneq.set_ylabel("Nonequilibrium")

    txt = fig.text(0.5, 0.02, '', ha='center', fontsize=11, bbox=dict(facecolor='white', alpha=0.8))

    def init():
        line_rho.set_data([], [])
        line_vel.set_data([], [])
        line_pres.set_data([], [])
        line_noneq.set_data([], [])
        txt.set_text('')
        return line_rho, line_vel, line_pres, line_noneq, txt

    def update(frame):
        U = u_history[frame]
        t = t_history[frame]

        rho = U[0].flatten()
        vel = (U[1] / U[0]).flatten()
        P_phys = get_pressure(U, gamma).flatten()
        P_phan = (U[3] / U[0]).flatten()
        P_noneq = P_phys - P_phan

        line_rho.set_data(x, rho)
        line_vel.set_data(x, vel)
        line_pres.set_data(x, P_phys)
        line_noneq.set_data(x, P_noneq)

        txt.set_text(f"Physical Time = {t:.4f}s | Frame {frame}/{len(u_history)-1}")
        return line_rho, line_vel, line_pres, line_noneq, txt

    anim = animation.FuncAnimation(fig, update, frames=len(u_history), init_func=init, blit=True)
    plt.close(fig)
    return HTML(anim.to_jshtml())

# Execute Sod Shock Tube: 150 Cells, Degree N=2 (3 solution points per cell, 450 global DOFs)
x, u_hist, t_hist, gamma, theta = run_solver(
    case_name="sod",
    N_cells=30,
    N=5,
    C_tau=0.15,  # Scaling constant for the relaxation timescale
    theta=1.0,   # Extra pressure feedback coefficient
    cfl=0.1     # Safe explicit CFL for high-order DG/FR with shocks
)

# Generate and display interactive video in Colab
generate_animation_html(x, u_hist, t_hist, gamma, theta, "sod")

# Execute Shu-Osher:  Cells, Degree N=2 ( global DOFs)
x_so, u_hist_so, t_hist_so, gamma_so, theta_so = run_solver(
    case_name="shu_osher",
    N_cells=200,
    N=3,
    C_tau=0.1,  # Pressure relaxation scaling
    theta=0.6,   # Bias towards the lagging / phantom pressure
    cfl=0.1
)

# Generate and display interactive video in Colab
#generate_animation_html(x_so, u_hist_so, t_hist_so, gamma_so, theta_so, "shu_osher")

# Generate a zoomed-in picture from x=0 to x=2

# Get the final state from the simulation history
U_final_so = u_hist_so[-1]

# Flatten the solution points and conserved variables for plotting
x_flat_so = x_so
rho_final_so = U_final_so[0].flatten()
vel_final_so = (U_final_so[1] / U_final_so[0]).flatten()
P_phys_final_so = get_pressure(U_final_so, gamma_so).flatten()
P_phan_final_so = (U_final_so[3] / U_final_so[0]).flatten()
P_noneq_final_so = P_phys_final_so - P_phan_final_so

# Filter data for the desired x-range (0 to 2)
x_min_zoom, x_max_zoom = 0.0, 3.0
zoom_mask = (x_flat_so >= x_min_zoom) & (x_flat_so <= x_max_zoom)

x_zoom = x_flat_so[zoom_mask]
rho_zoom = rho_final_so[zoom_mask]
vel_zoom = vel_final_so[zoom_mask]
P_phys_zoom = P_phys_final_so[zoom_mask]
P_noneq_zoom = P_noneq_final_so[zoom_mask]

# Create the zoomed-in plot
fig_zoom, axes_zoom = plt.subplots(2, 2, figsize=(10, 6))
fig_zoom.suptitle(f"Shu-Osher: Zoomed-in (x={x_min_zoom} to {x_max_zoom})", fontsize=14, fontweight='bold')

ax_rho_zoom, ax_vel_zoom = axes_zoom[0, 0], axes_zoom[0, 1]
ax_pres_zoom, ax_noneq_zoom = axes_zoom[1, 0], axes_zoom[1, 1]

# Plot density
ax_rho_zoom.plot(x_zoom, rho_zoom, 'b-', lw=2, label=r'$\rho$ (Density)')
ax_rho_zoom.set_title('Density')
ax_rho_zoom.set_xlim(x_min_zoom, x_max_zoom)
ax_rho_zoom.grid(True, linestyle=':', alpha=0.6)

# Plot velocity
ax_vel_zoom.plot(x_zoom, vel_zoom, 'r-', lw=2, label=r'$u$ (Velocity)')
ax_vel_zoom.set_title('Velocity')
ax_vel_zoom.set_xlim(x_min_zoom, x_max_zoom)
ax_vel_zoom.grid(True, linestyle=':', alpha=0.6)

# Plot physical pressure
ax_pres_zoom.plot(x_zoom, P_phys_zoom, 'g-', lw=2, label=r'$P_{phys}$ (Pressure)')
ax_pres_zoom.set_title('Pressure')
ax_pres_zoom.set_xlim(x_min_zoom, x_max_zoom)
ax_pres_zoom.grid(True, linestyle=':', alpha=0.6)

# Plot non-equilibrium pressure
ax_noneq_zoom.plot(x_zoom, P_noneq_zoom, 'k-', lw=1.5, label=r'$P_{phys} - P_{phan}$')
ax_noneq_zoom.set_title('Non-Equilibrium Pressure')
ax_noneq_zoom.set_xlim(x_min_zoom, x_max_zoom)
ax_noneq_zoom.grid(True, linestyle=':', alpha=0.6)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()